config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'pages#home'
  resources :caves
  get 'my_caves', to: 'caves#my_caves'
  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cafe.rb
class Cafe < ApplicationRecord
  belongs_to :user
  has_one_attached :photo
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :caves
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/caves_controller.rb
class CavesController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @caves = Cafe.all
  end

  def my_caves
    @caves = current_user.caves
    render :index
  end

  def show
    @cafe = Cafe.find(params[:id])
  end

  def new
    @cafe = current_user.caves.build
  end

  def create
    @cafe = current_user.caves.build(cafe_params)
    if @cafe.save
      redirect_to @cafe, notice: 'Cafe was successfully created.'
    else
      render :new
    end
  end

  private

  def cafe_params
    params.require(:cafe).permit(:name, :description, :menu, :photo)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/caves_helper.rb
module CavesHelper
end

app/views/caves/index.html.erb
<main role="main">
  <section class="jumbotron text-center">
    <div class="container">
      <h1 class="jumbotron-heading">Рестораны и кафе</h1>
    </div>
  </section>
  <div class="container">
    <div class="row">
      <% @caves.each do |cafe| %>
        <div class="col-md-4">
          <div class="album py-5 bg-light">
            <div class="container">
              <div class="row">
                <div class="cafe-card mb-4 box-shadow"> <!-- Изменен класс card на cafe-card -->
                  <% if cafe.photo.attached? %>
                    <%= image_tag cafe.photo, class: "card-img-top" %>
                  <% end %>
                  <div class="cafe-card-body"> <!-- Изменен класс card-body на cafe-card-body -->
                    <p class="card-text"><%= cafe.name %></p>
                    <p class="card-text"><%= cafe.description.truncate(100) %></p>
                    <%= link_to "View", cafe_path(cafe), class: "btn btn-sm btn-outline-secondary" %>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</main>

app/views/caves/new.html.erb
<section class="vh-100 gradient-custom">
  <div class="container py-5 h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-12 col-md-8 col-lg-6 col-xl-5">
        <div class="card bg-dark text-white" style="border-radius: 1rem;">
          <div class="card-body p-5 text-center">

            <div class="pb-5">

              <h2 class="fw-bold mb-2 text-uppercase">Создать кафе</h2>
              <p class="text-white-50 mb-5">Заполните информацию о вашем кафе</p>

              <%= form_with(model: @cafe, url: caves_path, method: :post, local: true) do |form| %>
                <div data-mdb-input-init class="form-outline form-white mb-4">
                  <%= form.text_field :name, class: "form-control form-control-lg", placeholder: "Название кафе" %>
                  <label class="form-label" for="cafeName">Название кафе</label>
                </div>

                <div data-mdb-input-init class="form-outline form-white mb-4">
                  <%= form.text_area :description, class: "form-control form-control-lg", placeholder: "Описание кафе" %>
                  <label class="form-label" for="cafeDescription">Описание кафе</label>
                </div>

                <div data-mdb-input-init class="form-outline form-white mb-4">
                  <%= form.text_area :menu, class: "form-control form-control-lg", placeholder: "Меню кафе" %>
                  <label class="form-label" for="cafeMenu">Меню кафе</label>
                </div>

                <div data-mdb-input-init class="form-outline form-white mb-4">
                  <%= form.file_field :photo, class: "form-control form-control-lg" %>
                  <label class="form-label" for="cafePhoto">Фото кафе</label>
                </div>

                <%= form.submit "Создать кафе", class: "btn btn-outline-light btn-lg px-5" %>
              <% end %>
            </div>

          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/caves/show.html.erb
<main role="main">
  <section class="content_show-section">
    <div class="menu">
      <h1 class="text-muted h1_show container_show_square"><%= @cafe.name %></h1><br>
        <div class= "container_show_square">
        <h2 class="text-muted">Меню</h2>
        <p class="lead text-muted"><%= @cafe.menu.gsub(/\n/, '<br>').html_safe %></p>
        </div>
    </div>
    <div class="image_show-container">
      <% if @cafe.photo.attached? %>
        <%= image_tag @cafe.photo, class: "img_cafe" %>
      <% end %>
      <div class="text_show-container container_show_square">
        <h2 class="text-muted">Описание</h2>
        <p class="lead text-muted"><%= @cafe.description %></p>
      </div>
    </div>
  </section>
</main>

app/views/custom_views/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-dark border-bottom border-body" data-bs-theme="dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">Restaurant</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarColor01">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <%= link_to 'Рестораны', caves_path, class: "nav-item nav-link"%>
          <%= link_to 'Создать', new_cafe_path, class: "nav-item nav-link"%>
          <%= link_to 'Мои кафе', my_caves_path, class: "nav-item nav-link"%>
        </ul>
        <form class="d-flex" role="search">
          <% if current_user.present? %>
            <%= link_to 'Выход', destroy_user_session_path, class: "btn btn-outline-light me-2", data: { "turbo-method": :delete } %>
          <% else %>
            <%= link_to 'Вход', new_user_session_path, class: "btn btn-outline-light me-2" %>
            <%= link_to 'Регистрация', new_user_registration_path, class: "btn btn-outline-light me-2" %>
          <% end %>
        </form>
      </div>
    </div>
  </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Restaurant</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </head>

  <body>
    <%= render 'custom_views/navbar' %>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>
  </body>
</html>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>